// <auto-generated />
namespace DogrudanTemin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1401 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1401));
        
        string IMigrationMetadata.Id
        {
            get { return "202101132240390_1401"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
